language: go
os:
  - linux
go:
  - stable
git:
  depth: 1
before_install:
  - go get -v golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
env:
  global:
    - GIMME_DEBUG=1
    - GO111MODULE=on
    - GOFLAGS='-mod=vendor'
install: skip
script: skip
notifications:
  email: false
